### ISSUE TITLE
Decide on a regular meeting cadence

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-micromobility-aggregation-privacy#1]
It seems like once a month is good for the team. I propose we save an hour every 3rd Wednesday of the month at 3:30pm Central Time. Open to alternatives to that but I think we'll save effort if we have a standard time set in advance.

**Comment by mateoclarke** [comment]
Hey y'all, how do y'all feel about setting a monthly check-in time? My proposed 3rd Wednesday is coming up next week on 10/16. Would 3:30pm Central Time work for y'all on that date?

@inc0 
@mlinksva 
@annafil

**Comment by mateoclarke** [comment]
10/16 is tomorrow so it doesn't seems like that will work for everyone.

Can we try to do next Wed 10/23?

@inc0
@mlinksva
@annafil

**Comment by annafil** [comment]
I can make next Wed the 23rd! For now my calendar is open 9-10PT and 1PM PT onwards.

**Comment by mlinksva** [comment]
Wed 23rd 9-10PT should work for me as well.

**Comment by mateoclarke** [comment]
Great, the call has been scheduled and we can discuss this more on Wednesday. Please let me know if you didn't get the calendar invite.

**Comment by annafil** [comment]
🖐 I didn't receive a calendar invite yet :)

**Comment by mlinksva** [comment]
Nor did I. I could still call in about 9-930am PT but will be in transit due to a change in my itinerary.

**Comment by mateoclarke** [comment]
Sorry! The invite has been updated now.

**Comment by mateoclarke** [comment]
Nov 20th, 3rd wed at 9am PT is good for Michal, Anna, Mike

**Comment by mateoclarke** [comment]
Calendar item sent for a recurring meeting at 9am PT on the 3rd Wednesday of the month through May 2020
